### PR TITLE
Fix By TDD788

### PR DESCRIPTION
**Pull request by TDD788**

### CODE REVIEW

**Comment by Mizumo-prjkt** [comment]
I'll review this later since there's too much changes

**Comment by Mizumo-prjkt** [comment]
i think i prefer keeping the dsms to keep compatibility with stock but idk what will happen without it since dsms is a samsung core component

**Comment by TDD788** [comment]
> i think i prefer keeping the dsms to keep compatibility with stock but idk what will happen without it since dsms is a samsung core component

Don't worry, for that I recommend the prebuilt twrp dms

**Comment by Mizumo-prjkt** [comment]
use dd instead of cp with bs to 128M

i prefer the byte integrity to be deadspot accurate on copying system partition

**Review by Mizumo-prjkt — APPROVED** [review]

**Review by Mizumo-prjkt — APPROVED** [review]

**Comment by TDD788** [comment]
Use my new multidisabler, the others are obsolete.

**Comment by TDD788** [comment]
Get in form https://github.com/TDD788/A12s-DevTree

**Review by Mizumo-prjkt — APPROVED** [review]

**Comment by Mizumo-prjkt** [comment]
close pull request because github annoying

**Pull request closed without merging**
